"""empty message

Revision ID: 574b7a7cc20
Revises: a242cc1f12
Create Date: 2014-04-02 01:44:42.096167

"""

# revision identifiers, used by Alembic.
revision = '574b7a7cc20'
down_revision = 'a242cc1f12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('subreddit', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'subreddit')
    ### end Alembic commands ###
